indent-width = 2

[format]
quote-style = 'single'

[lint]
ignore = [
  'E501',
  'FIX002',
  'PLR2004'  # most numbers are not magic
]
extend-select = [
  'A',
  'B',    # flake8-bugbear
  'E',    # pycodestyle
  'EXE',
  'F',    # Pyflakes
  'FA',
  'FIX',
  'FLY',
  'I',    # isort
  'PERF', # performance
  'PLC',  # pylint conventions
  'PLE',  # pylint errors
  'PLR',  # pylint refactors
  'PLW',  # pylint warnings
  'S',    # flake8-bandit
  'SIM',  # flake8-simplify
  'UP',   # pyupgrade
  'W'     # pycodestyle
]

[lint.isort]
known-first-party = [
  'generate_osv_advisories',
  'user_agent',
  'typings'
]
